import { products } from "@/data/products";
import { categories } from "@/data/categories";
import { reviews } from "@/data/reviews";
import type { AdminDatabase, AdminOrder } from "@/lib/admin/types";
import { createDefaultSiteSettings, defaultBlogPosts } from "@/lib/admin/site-defaults";

const MOCK_ORDERS: AdminOrder[] = [
  {
    id: "AM-20260820001",
    date: "2026-08-20",
    status: "delivered",
    customerName: "Алина Козлова",
    customerEmail: "alina@example.com",
    customerPhone: "+7 916 123-45-67",
    items: [
      { slug: "bakuchiol-night", name: "Bakuchiol Night", qty: 1, price: 8900, image: "/images/bakuchiol-v2.webp" },
      { slug: "peptide-dew", name: "Peptide Dew", qty: 1, price: 8200, image: "/images/peptide-v2.webp" },
    ],
    delivery: {
      carrier: "cdek",
      mode: "pickup",
      price: 0,
      minDays: 2,
      maxDays: 4,
      city: "Москва",
      pickupPoint: {
        id: "msk-1",
        carrier: "cdek",
        city: "Москва",
        name: "СДЭК ПВЗ Тверская",
        address: "ул. Тверская, 12",
        schedule: "10:00–22:00",
      },
    },
    payment: "sbp",
    subtotal: 17100,
    discount: 0,
    shipping: 0,
    total: 17100,
    trackingNumber: "CDEK-8829103",
  },
  {
    id: "AM-20260822002",
    date: "2026-08-22",
    status: "shipped",
    customerName: "Мария Соколова",
    customerEmail: "maria@example.com",
    customerPhone: "+7 903 555-12-34",
    items: [
      { slug: "cica-repair", name: "Cica Repair", qty: 2, price: 7800, image: "/images/cica-v2.webp" },
    ],
    delivery: {
      carrier: "russian_post",
      mode: "courier",
      price: 390,
      minDays: 3,
      maxDays: 7,
      city: "Санкт-Петербург",
      address: "Невский пр., 45, кв. 12",
    },
    payment: "card",
    subtotal: 15600,
    discount: 1560,
    shipping: 390,
    total: 14430,
    promoCode: "AMBEAUTY10",
    trackingNumber: "RP-4410291",
  },
  {
    id: "AM-20260825003",
    date: "2026-08-25",
    status: "processing",
    customerName: "Елена Волкова",
    customerEmail: "elena@example.com",
    customerPhone: "+7 925 777-88-99",
    items: [
      { slug: "hydra-cream", name: "Hydra Cream", qty: 1, price: 6900, image: "/images/cica-v2.webp" },
      { slug: "micellar-water", name: "Micellar Water", qty: 1, price: 3200, image: "/images/peptide-v2.webp" },
    ],
    delivery: {
      carrier: "yandex",
      mode: "courier",
      price: 490,
      minDays: 1,
      maxDays: 2,
      city: "Москва",
      address: "ул. Арбат, 10",
    },
    payment: "sbp",
    subtotal: 10100,
    discount: 0,
    shipping: 490,
    total: 10590,
  },
  {
    id: "AM-20260827004",
    date: "2026-08-27",
    status: "pending",
    customerName: "Дарья Лебедева",
    customerEmail: "darya@example.com",
    customerPhone: "+7 981 222-33-44",
    items: [
      { slug: "velvet-tint", name: "Velvet Tint", qty: 3, price: 4200, image: "/images/hero-v2.webp" },
    ],
    delivery: {
      carrier: "cdek",
      mode: "pickup",
      price: 290,
      minDays: 2,
      maxDays: 5,
      city: "Казань",
      pickupPoint: {
        id: "kzn-1",
        carrier: "cdek",
        city: "Казань",
        name: "СДЭК ПВЗ Баумана",
        address: "ул. Баумана, 58",
      },
    },
    payment: "card",
    subtotal: 12600,
    discount: 0,
    shipping: 290,
    total: 12890,
  },
  {
    id: "AM-20260828005",
    date: "2026-08-28",
    status: "processing",
    customerName: "Ольга Петрова",
    customerEmail: "olga@example.com",
    customerPhone: "+7 915 444-55-66",
    items: [
      { slug: "bakuchiol-night", name: "Bakuchiol Night", qty: 1, price: 8900, image: "/images/bakuchiol-v2.webp" },
    ],
    delivery: {
      carrier: "cdek",
      mode: "courier",
      price: 0,
      minDays: 1,
      maxDays: 3,
      city: "Москва",
      address: "Ленинский пр., 99, кв. 84",
    },
    payment: "sbp",
    subtotal: 8900,
    discount: 0,
    shipping: 0,
    total: 8900,
  },
];

export function seedDatabase(): AdminDatabase {
  return {
    version: 3,
    updatedAt: new Date().toISOString(),
    products: products.map((p, i) => ({
      ...p,
      stock: [24, 18, 31, 12, 45, 8, 22, 15, 27][i] ?? 20,
      published: true,
    })),
    categories: categories.map((c, i) => ({
      ...c,
      published: true,
      sortOrder: i,
    })),
    site: createDefaultSiteSettings(),
    blog: defaultBlogPosts(),
    orders: MOCK_ORDERS,
    reviews: reviews.map((r) => ({ ...r, published: true })),
    promos: [
      { code: "AMBEAUTY10", discountPercent: 0.1, active: true, uses: 42 },
      { code: "WELCOME15", discountPercent: 0.15, active: true, uses: 18 },
      { code: "GLOW20", discountPercent: 0.2, active: false, uses: 0 },
    ],
  };
}
